/*
 * M.B. - ABA Oman International School (2019-2020)
 * 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ia;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DecimalFormat;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mark
 */

public class ReportMenu extends javax.swing.JFrame

{
    public class FoodObject {
        public String FoodName = "";
        public int ImportDistance = 0;
        public String ImportCountry = "";
        public int QuantityConsumed = 0;
        public int QuantityWasted = 0;
        public int QuantityPurchased = 0;
        public int TotalPrice = 0;
        public String DateInput = "";
        public int TotalCustomers = 0;

        public FoodObject(String FoodName, int ImportDistance, String ImportCountry, int QuantityConsumed,
                int QuantityWasted, int QuantityPurchased, int TotalPrice) {
            this.FoodName = FoodName;
            this.ImportDistance = ImportDistance;
            this.ImportCountry = ImportCountry;
            this.QuantityConsumed = QuantityConsumed;
            this.QuantityWasted = QuantityWasted;
            this.QuantityPurchased = QuantityPurchased;
            this.TotalPrice = TotalPrice;

        }

    }

    public static DecimalFormat df = new DecimalFormat("0.00");
    public static DecimalFormat wn = new DecimalFormat("0");

    public LinkedList<FoodObject> FoodList = new LinkedList<>();

    static void setVisable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // To change body of generated methods, choose
                                                                       // Tools | Templates.
    }

    /**
     * Creates new form
     */
    public ReportMenu() {
        initComponents();
        ReportMenuHeader();
    }

    private void ReportMenuHeader() {
        Report.setText("==============================================" + "\n" + "Report for the Chedi @ Oman" + "\n"
                + "==============================================" + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        FoodName = new javax.swing.JLabel();
        FoodNameInput = new javax.swing.JTextField();
        QuantityPurchased = new javax.swing.JLabel();
        QuantityPurchasedInput = new javax.swing.JTextField();
        QuantityWasted = new javax.swing.JLabel();
        QuantityWastedInput = new javax.swing.JTextField();
        ImportCountry = new javax.swing.JLabel();
        ImportCountryInput = new javax.swing.JTextField();
        TotalPrice = new javax.swing.JLabel();
        TotalPriceInput = new javax.swing.JTextField();
        QuantityConsumed = new javax.swing.JLabel();
        QuantityConsumedInput = new javax.swing.JTextField();
        ImportDistance = new javax.swing.JLabel();
        ImportDistanceInput = new javax.swing.JTextField();
        TotalCustomers = new javax.swing.JLabel();
        TotalCustomersInput = new javax.swing.JTextField();
        AddToReport = new javax.swing.JButton();
        Date = new javax.swing.JLabel();
        DateInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Report = new javax.swing.JTextArea();
        Print = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ia/Teehee.png"))); // NOI18N

        FoodName.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        FoodName.setForeground(new java.awt.Color(51, 153, 0));
        FoodName.setText("Food Name:");

        FoodNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodNameInputActionPerformed(evt);
            }
        });

        QuantityPurchased.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        QuantityPurchased.setForeground(new java.awt.Color(51, 153, 0));
        QuantityPurchased.setText("Quantity Purchased (Kg):");

        QuantityPurchasedInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityPurchasedInputActionPerformed(evt);
            }
        });

        QuantityWasted.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        QuantityWasted.setForeground(new java.awt.Color(51, 153, 0));
        QuantityWasted.setText("Quantity Wasted( Kg):");

        QuantityWastedInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityWastedInputActionPerformed(evt);
            }
        });

        ImportCountry.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        ImportCountry.setForeground(new java.awt.Color(51, 153, 0));
        ImportCountry.setText("Import Country:");

        ImportCountryInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportCountryInputActionPerformed(evt);
            }
        });

        TotalPrice.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        TotalPrice.setForeground(new java.awt.Color(51, 153, 0));
        TotalPrice.setText("Total Price (OMR):");

        TotalPriceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceInputActionPerformed(evt);
            }
        });

        QuantityConsumed.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        QuantityConsumed.setForeground(new java.awt.Color(51, 153, 0));
        QuantityConsumed.setText("Quantity Consumed (Kg):");

        QuantityConsumedInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityConsumedInputActionPerformed(evt);
            }
        });

        ImportDistance.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        ImportDistance.setForeground(new java.awt.Color(51, 153, 0));
        ImportDistance.setText("Import Distance (Km):");

        ImportDistanceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportDistanceInputActionPerformed(evt);
            }
        });

        TotalCustomers.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        TotalCustomers.setForeground(new java.awt.Color(51, 153, 0));
        TotalCustomers.setText("Total Customers:");

        TotalCustomersInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalCustomersInputActionPerformed(evt);
            }
        });

        AddToReport.setText("Add");
        AddToReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToReportActionPerformed(evt);
            }
        });

        Date.setFont(new java.awt.Font("Avenir Next Condensed", 1, 24)); // NOI18N
        Date.setForeground(new java.awt.Color(51, 153, 0));
        Date.setText("Date (dd/mm/yyyy):");

        DateInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateInputActionPerformed(evt);
            }
        });

        Report.setColumns(20);
        Report.setRows(5);
        jScrollPane1.setViewportView(Report);

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(15, 15, 15).addComponent(BackButton)
                                .addGap(126, 126, 126).addComponent(Title))
                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(20, 20, 20).addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AddToReport, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(9, 9, 9)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(ImportCountry)
                                                                        .addComponent(QuantityWasted))
                                                                .addGap(5, 5, 5))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(QuantityPurchased)
                                                                        .addComponent(FoodName))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(QuantityConsumed).addComponent(TotalPrice)
                                                        .addComponent(ImportDistance)).addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ImportDistanceInput,
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                .addComponent(ImportCountryInput,
                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(TotalPriceInput).addComponent(QuantityConsumedInput)
                                                .addComponent(FoodNameInput).addComponent(QuantityPurchasedInput)
                                                .addComponent(QuantityWastedInput))))
                                .addGap(75, 75, 75).addGroup(
                                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                        .createSequentialGroup().addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(Date,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(TotalCustomers,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(TotalCustomersInput)
                                                                .addComponent(DateInput,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 149,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(Title,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(17, 17, 17).addComponent(BackButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(FoodNameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(QuantityPurchased).addComponent(QuantityPurchasedInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(QuantityWasted).addComponent(QuantityWastedInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ImportCountry).addComponent(ImportCountryInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(TotalPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TotalPrice))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(QuantityConsumed).addComponent(QuantityConsumedInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ImportDistance).addComponent(ImportDistanceInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addComponent(AddToReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(144, Short.MAX_VALUE))
                                .addGroup(
                                        jPanel1Layout.createSequentialGroup().addComponent(jScrollPane1)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(TotalCustomers)
                                                                        .addComponent(TotalCustomersInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(Date)
                                                                        .addComponent(DateInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup().addGap(28, 28, 28)
                                                                        .addComponent(Print,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                62,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(163, 163, 163)))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FoodNameInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FoodNameInputActionPerformed

    }// GEN-LAST:event_FoodNameInputActionPerformed

    private void ImportCountryInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ImportCountryInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ImportCountryInputActionPerformed

    private void AddToReportActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddToReportActionPerformed

        Report.setText(Report.getText() + "\n" + "Food: " + FoodNameInput.getText() + "\t" + "From: "
                + ImportCountryInput.getText() + "\t" + "(Around " + ImportDistanceInput.getText() + " Km From Oman)"
                + "\n" + "Quantity Purchased (KG): " + QuantityPurchasedInput.getText() + "\n"
                + "Quantity Consumed (KG): " + QuantityConsumedInput.getText() + "\n" + "Quantity Wasted (KG): "
                + QuantityWastedInput.getText() + "\n" + "          Total Price for Food (OMR): "
                + TotalPriceInput.getText() + "\n"
                + "*****************************************************************************");

        FoodList.add(new FoodObject(FoodName.getText(), Integer.parseInt(ImportDistanceInput.getText()),
                ImportCountry.getText(), Integer.parseInt(QuantityConsumedInput.getText()),
                Integer.parseInt(QuantityWastedInput.getText()), Integer.parseInt(QuantityPurchasedInput.getText()),
                Integer.parseInt(TotalPriceInput.getText())));

        FoodNameInput.setText("");
        ImportCountryInput.setText("");
        ImportDistanceInput.setText("");
        QuantityWastedInput.setText("");
        QuantityPurchasedInput.setText("");
        TotalPriceInput.setText("");
        QuantityConsumedInput.setText("");

        // textfield.setText(null); //or use this

    }// GEN-LAST:event_AddToReportActionPerformed

    private void DateInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DateInputActionPerformed

    }// GEN-LAST:event_DateInputActionPerformed

    private void QuantityPurchasedInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QuantityPurchasedInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_QuantityPurchasedInputActionPerformed

    private void TotalCustomersInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TotalCustomersInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TotalCustomersInputActionPerformed

    private void QuantityWastedInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QuantityWastedInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_QuantityWastedInputActionPerformed

    private void ImportDistanceInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ImportDistanceInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ImportDistanceInputActionPerformed

    private void QuantityConsumedInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QuantityConsumedInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_QuantityConsumedInputActionPerformed

    private void TotalPriceInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TotalPriceInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_TotalPriceInputActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:

        int TotalQuantityProduced = 0;
        System.out.println(FoodList.size()); // test to see if the linked list collects lists

        for (int i = 0; i < FoodList.size(); i++) {
            TotalQuantityProduced += FoodList.get(i).QuantityPurchased;
        }

        int TotalProductionEmissions = TotalQuantityProduced * 20; // 20 is the value of C02 emissions per KG of average
                                                                   // food production

        double TotalQuantityConsumed = 0.0;

        for (int i = 0; i < FoodList.size(); i++) {
            TotalQuantityConsumed += FoodList.get(i).QuantityConsumed;
        }

        double TotalConsumptionEmissions = TotalQuantityConsumed * 18.133333; // 18.1333333 is the value of C02
                                                                              // emissions per KG of average food
                                                                              // consumption

        double TotalQuantityWasted = 0.0;

        for (int i = 0; i < FoodList.size(); i++) {
            TotalQuantityWasted += FoodList.get(i).QuantityWasted;
        }

        double TotalWasteEmissions = TotalQuantityWasted * 6.75; // 6.75 is the value of C02 emissions per KG of average
                                                                 // food wastage, reduced value due to Chedi's Recycling
                                                                 // amount.
        double TotalEmissions = TotalWasteEmissions + TotalConsumptionEmissions + TotalProductionEmissions;

        int tc = Integer.parseInt(TotalCustomersInput.getText());

        double AverageWastePerCustomer = TotalEmissions / tc;

        int TotalImportDistance = 0;

        for (int i = 0; i < FoodList.size(); i++) {
            TotalImportDistance += FoodList.get(i).ImportDistance;
        }

        double AverageImportDistance = TotalImportDistance / FoodList.size();

        int max = -1;
        String MaxImportCountry = "";

        // Linear search through the linked list using an iterative function to find the
        // country that has the max import distance (thus highest CO2 emissions for
        // importing)
        for (int i = 0; i < FoodList.size(); i++) {
            int currFoodObject = FoodList.get(i).ImportDistance;
            if (currFoodObject > max) {
                max = currFoodObject;
                MaxImportCountry = FoodList.get(i).ImportCountry;
            }

        }

        double CarEmissions = (TotalEmissions * 1000) / 411; // converting the total emissions from KG to G, then
                                                             // dividing it by 411 (the average amount of carbon emitted
                                                             // from the average petrol car per mile, in g)

        double PlaneEmissions = TotalEmissions / 24.0404; // 24.0404 is the average amount of carbon (KG) the average
                                                          // passenger plane produces per every mile

        int TotalFoodPrice = 0;
        for (int i = 0; i < FoodList.size(); i++) {

            TotalFoodPrice += FoodList.get(i).TotalPrice;

        }

        double TotalMoneyWasted = (TotalFoodPrice / TotalQuantityProduced) * TotalQuantityWasted;

        double OppertunityCost = TotalMoneyWasted / 36; // 36 OMR is the amount required to sponser an Omani student's
                                                        // daily school meals for an entire year with Dar Al Atta

        final File file = new File("NewReport" + DateInput.getText() + ".txt");
        final File parent_directory = file.getParentFile();

        if (null != parent_directory) {
            parent_directory.mkdirs();
        }
        FileWriter fileWriter = null;

        try {
            fileWriter = new FileWriter("NewReport" + DateInput.getText() + ".txt");
        } catch (IOException ex) {
            Logger.getLogger(ReportMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        PrintWriter printWriter = new PrintWriter(fileWriter);

        printWriter.println("FoodReport for  the date :  " + DateInput.getText());
        printWriter.println(Report.getText());
        printWriter.println("----------------------------------------------");
        printWriter.println(
                "Your Total Production Emissions were:   " + df.format(TotalProductionEmissions) + " KG of CO2");
        printWriter.println(
                "Your Total Consumption Emissions were:   " + df.format(TotalConsumptionEmissions) + " KG of CO2");
        printWriter.println("Your Total Production Emissions were:   " + df.format(TotalWasteEmissions) + " KG of CO2");
        printWriter.println("----------------------------------------------");
        printWriter.println("Your Average Waste of food per Customer was:   " + df.format(AverageWastePerCustomer)
                + " KG of wasted food");
        printWriter.println("Imports from:   " + MaxImportCountry + " caused the most CO2 emissions");
        printWriter.println("Your Total Import Distance was:   " + df.format(TotalImportDistance) + " KM");
        printWriter.println("----------------------------------------------");
        printWriter.println("Your Carbon Emissions are equivalent to:   ");
        printWriter.println(" . Driving an average petrol car for:   " + df.format(CarEmissions) + " MILES");
        printWriter.println("");
        printWriter.println("       ______ ");
        printWriter.println("      /|_||_\\`.__ ");
        printWriter.println("     (   _    _ _\\");
        printWriter.println("=-----`-(_)--(_)-'");
        printWriter.println("");
        printWriter.println("----------------------------------------------");
        printWriter.println(" . Flying an average passenger plane for:   " + df.format(PlaneEmissions) + " MILES");
        printWriter.println("");
        printWriter.println("     __________");
        printWriter.println("        \\ ___\\_");
        printWriter.println(" =  = ==(________D");
        printWriter.println("          \\_____\\________________________________");
        printWriter.println("          /     o O o o o o O O o o o o o o O o  |\\_");
        printWriter.println("          `~-.__        ___..----..                  )");
        printWriter.println("                ˆ-----~~\\___________/---------------/");
        printWriter.println("                   =  ===(_________D");
        printWriter.println("");
        printWriter.println("----------------------------------------------");
        printWriter.println(
                " . Lastly, the money you wasted could have sponsored the daily meals for an entire year for:   "
                        + wn.format(OppertunityCost) + " Local Omani students with Dar Al Atta");
        printWriter.println("");
        printWriter.println("          ( ");
        printWriter.println("            ) ");
        printWriter.println("       __..---..__");
        printWriter.println("  ,--='  /  |  \\  `=--.");
        printWriter.println(" :--..____________..---; ");
        printWriter.println("  \\.,_____________,.//");
        printWriter.println("");
        printWriter.println("----------------------------------------------");

        printWriter.close();

    }// GEN-LAST:event_PrintActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        {
            this.setVisible(false);
            new mainmenu().setVisible(true); // Main Form to show after the Login Form..
        }

    }// GEN-LAST:event_BackButtonActionPerformed
    /// *
    // /**
    // * @param args the command line arguments
    // */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    /// (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    /// default look and feel.
    // * For details see
    /// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    /// javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(ReportMenu.class.getName()).log(java.util.logging.Level.SEVERE,
    /// null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(ReportMenu.class.getName()).log(java.util.logging.Level.SEVERE,
    /// null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(ReportMenu.class.getName()).log(java.util.logging.Level.SEVERE,
    /// null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(ReportMenu.class.getName()).log(java.util.logging.Level.SEVERE,
    /// null, ex);
    // }
    // //</editor-fold>
    // //</editor-fold>
    //
    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new ReportMenu().setVisible(true);
    // }
    // });
    //

    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddToReport;
    public javax.swing.JButton BackButton;
    private javax.swing.JLabel Date;
    private javax.swing.JTextField DateInput;
    private javax.swing.JLabel FoodName;
    private javax.swing.JTextField FoodNameInput;
    private javax.swing.JLabel ImportCountry;
    private javax.swing.JTextField ImportCountryInput;
    private javax.swing.JLabel ImportDistance;
    private javax.swing.JTextField ImportDistanceInput;
    public javax.swing.JButton Print;
    private javax.swing.JLabel QuantityConsumed;
    private javax.swing.JTextField QuantityConsumedInput;
    private javax.swing.JLabel QuantityPurchased;
    private javax.swing.JTextField QuantityPurchasedInput;
    private javax.swing.JLabel QuantityWasted;
    private javax.swing.JTextField QuantityWastedInput;
    private javax.swing.JTextArea Report;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TotalCustomers;
    private javax.swing.JTextField TotalCustomersInput;
    private javax.swing.JLabel TotalPrice;
    private javax.swing.JTextField TotalPriceInput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
